// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5cnff5Yo9fDfXTxxvnvj9AlXLG7JYgQo',
    appId: '1:1015282084100:web:31414a455d03b8ff964851',
    messagingSenderId: '1015282084100',
    projectId: 'appgestioncontacts',
    authDomain: 'appgestioncontacts.firebaseapp.com',
    storageBucket: 'appgestioncontacts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3nAcn1jfS9lWEYg2xxkHQkvCj48cE-rI',
    appId: '1:1015282084100:android:2449856d8e938a57964851',
    messagingSenderId: '1015282084100',
    projectId: 'appgestioncontacts',
    storageBucket: 'appgestioncontacts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz1WKgCPXP1iVrVIbfI4x4EHLc2oK8VNA',
    appId: '1:1015282084100:ios:8449d7f5a57f0ad4964851',
    messagingSenderId: '1015282084100',
    projectId: 'appgestioncontacts',
    storageBucket: 'appgestioncontacts.firebasestorage.app',
    iosBundleId: 'com.example.appGestionContacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz1WKgCPXP1iVrVIbfI4x4EHLc2oK8VNA',
    appId: '1:1015282084100:ios:8449d7f5a57f0ad4964851',
    messagingSenderId: '1015282084100',
    projectId: 'appgestioncontacts',
    storageBucket: 'appgestioncontacts.firebasestorage.app',
    iosBundleId: 'com.example.appGestionContacts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5cnff5Yo9fDfXTxxvnvj9AlXLG7JYgQo',
    appId: '1:1015282084100:web:0fa81b78cefaff54964851',
    messagingSenderId: '1015282084100',
    projectId: 'appgestioncontacts',
    authDomain: 'appgestioncontacts.firebaseapp.com',
    storageBucket: 'appgestioncontacts.firebasestorage.app',
  );
}
